### PR TITLE
Add new RAG3 game

### PR DESCRIPTION
**Pull request by jul3x**
Due to DEMO release of my game - I would like to add it to SFML projects list :)

Github: https://github.com/jul3x/RAG3

### CODE REVIEW

**Comment by jul3x** [comment]
Hi @eXpl0it3r, can I help you somehow in merging this PR?

**Comment by eXpl0it3r** [comment]
Sorry, slightly preoccupied with other projects and well some gaming 😄 

I'll get around to it tomorrow though!

**Comment by jul3x** [comment]
No worries, have a good time :D

**Comment by eXpl0it3r** [comment]
Thanks a lot for making this PR! 🙂 

And I'm sorry it took so long. I had recently re-installed my PC and had to setup my local development environment again first.

The changes have been published! 🥳

**Comment by jul3x** [comment]
Thank you for the opportunity! Best wishes :)

**Pull request merged**
